version: '3'
services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile.reactUI
    ports:
      - "5173:5173"
    depends_on:
      - db

  nodebackend:
    build:
      context: ./backend
      dockerfile: Dockerfile.node
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./backend:/app
    environment:
      - NODE_ENV=production

  db:
    image: mongo:latest
    volumes:
      - db:/data/db
    ports:
      - "27017:27017"

volumes:
  db:
